---
title: "Make auROCs for Model Fairness Evaluations"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

### Set Up Environment


```{r, packages_workflow}
#| message: false
#| warning: false

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()
```


```{r, packages_script}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(tidyposterior)
library(kableExtra, exclude = "group_rows")


theme_set(theme_classic()) 
```


```{r source_functions}
#| output: false

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
# CHTC support functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/chtc/static_files/fun_chtc.R?raw=true")
```

```{r, absolute_paths}
path_processed <- format_path(str_c("studydata/risk/data_processed/lag"))
path_models_lag <- format_path(str_c("studydata/risk/models/lag"))
```

## Helper function

function
```{r}
get_auroc_by_dem <- function(df, var) {
  # df should be dataframe with demographic features and predictions
  # var should be character or factor variable in df
  
  var_tmp <- df |> 
      pull(get(var))
   
  var_levels <- 
     if (class(var_tmp) != "factor") {
       levels(as.factor(var_tmp))
     } else levels(var_tmp)
  
  # create empty tibble with outer split nums
  auroc <- tibble(outer_split_num = unique(df$outer_split_num)) |> 
    arrange(outer_split_num) 
    
  for (level in var_levels) {
     auroc_level <- df |>
       filter(get(var) == level) |> 
       nest(.by = outer_split_num, .key = "preds") |> 
       mutate(auroc = map(preds, \(preds) roc_auc(preds, prob_beta, 
                                             truth = label))) |> 
       select(-preds) |> 
       unnest(auroc) |> 
       select(-c(.estimator, .metric)) |> 
       rename(!!level:=.estimate)
     
     auroc <- auroc |> 
       left_join(auroc_level, by = "outer_split_num")
  }
  
  return(auroc)
}
```


## Function that will map over lead times and demographic vars

Step 1 load preds and feats and link

```{r}
preds_out <- read_rds(here::here(path_models, str_c("outer_preds_dem_6_x_5_1week_", 
                                                    lead, "_v1_nested_main.rds")))

feat <- read_csv(here::here(path_processed, str_c("features_", lead, "lag_v1.csv.xz")),
                 col_types = cols()) |> 
  select(label_num, subid, dttm_label, lapse, demo_age, demo_sex, demo_income, demo_race) |> 
  mutate(label = if_else(lapse == "yes", "Lapse", "No lapse"),
         id_obs = label_num) |> 
  select(-c(label_num, lapse)) |> 
  arrange(label_num) 

feat_preds <- feat |> 
  right_join(preds_out, by = c("id_obs", "label"))

# nrow(feat)
# nrow(preds_out) # should be nrow(feat) * 3
# nrow(feat_preds) # should be same as nrow(preds_out)
```


Step 2 dichotomize demographics
```{r}
feat_preds <- feat_preds |> 
  mutate(demo_sex = if_else(demo_sex == "Female", "female", "male"),
         demo_race = if_else(demo_race == "White/Caucasian", "non-Hispanic white", "not white"),
         demo_income = if_else(demo_income < 1560, "below poverty", "above poverty"))
```


Step 3 calculate auROCs using probability corrected (prob_beta) probabilities.   

```{r}
auroc_dem <- get_auroc_by_dem(df = feat_preds, var = "demo_sex") |> 
  left_join(get_auroc_by_dem(df = feat_preds, var = "demo_race"), by = "outer_split_num") |> 
  left_join(get_auroc_by_dem(df = feat_preds, var = "demo_income"), by = "outer_split_num")
```


Check missing values
```{r}

```

Step 4 calculate median posterior probabilities


## Save out final tibbles
```{r}
auroc_dem |> 
  write_csv(here::here(path_models, str_c("test_auroc_dem_6_x_5_1week_", lead, 
                                          "_v1_nested.csv")))  
```
