---
title: "Make Shapley Data for Figures"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
html-table-processing: none
---

```{r}
#| message: false
#| warning: false

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true"))
library(kableExtra, exclude = "group_rows")

path_models <- format_path(str_c("studydata/risk/models/lag"))
```

## Z score and Normalize SHAP values

```{r}
shap_0 <- read_rds(here::here(path_models, 
                              "outer_shaps_1week_0_v1_nested_main.rds")) |> 
  group_by(variable) |> 
  # Z score variables by individual feature items
  mutate(feature_score_z = (rfvalue - mean(rfvalue))/sd(rfvalue)) |> 
  # Put future efficacy in correct direction
  mutate(feature_score_z = if_else(str_detect(variable, "ema_10"),
                                        feature_score_z * (-1),
                                        feature_score_z)) |> 
  # normalize feature score to 0-1 scale
  mutate(feature_score_z_scaled = (feature_score_z - min(feature_score_z))/(max(feature_score_z)-min(feature_score_z))) |> 
  glimpse()
```


```{r}
shap_24 <- read_rds(here::here(path_models, 
                              "outer_shaps_1week_24_v1_nested_main.rds")) |> 
  group_by(variable) |> 
  # Z score variables by individual feature items
  mutate(feature_score_z = (rfvalue - mean(rfvalue))/sd(rfvalue)) |> 
  # Put future efficacy in correct direction
  mutate(feature_score_z = if_else(str_detect(variable, "ema_10"),
                                        feature_score_z * (-1),
                                        feature_score_z)) |> 
  # normalize feature score to 0-1 scale
  mutate(feature_score_z_scaled = (feature_score_z - min(feature_score_z))/(max(feature_score_z)-min(feature_score_z))) |> 
  glimpse()
```

```{r}
shap_72 <- read_rds(here::here(path_models, 
                              "outer_shaps_1week_72_v1_nested_main.rds")) |> 
  group_by(variable) |> 
  # Z score variables by individual feature items
  mutate(feature_score_z = (rfvalue - mean(rfvalue))/sd(rfvalue)) |> 
  # Put future efficacy in correct direction
  mutate(feature_score_z = if_else(str_detect(variable, "ema_10"),
                                        feature_score_z * (-1),
                                        feature_score_z)) |> 
  # normalize feature score to 0-1 scale
  mutate(feature_score_z_scaled = (feature_score_z - min(feature_score_z))/(max(feature_score_z)-min(feature_score_z))) |> 
  glimpse()
```

```{r}
shap_168 <- read_rds(here::here(path_models, 
                              "outer_shaps_1week_168_v1_nested_main.rds")) |> 
  group_by(variable) |> 
  # Z score variables by individual feature items
  mutate(feature_score_z = (rfvalue - mean(rfvalue))/sd(rfvalue)) |> 
  # Put future efficacy in correct direction
  mutate(feature_score_z = if_else(str_detect(variable, "ema_10"),
                                        feature_score_z * (-1),
                                        feature_score_z)) |> 
  # normalize feature score to 0-1 scale
  mutate(feature_score_z_scaled = (feature_score_z - min(feature_score_z))/(max(feature_score_z)-min(feature_score_z))) |> 
  glimpse()
```


```{r}
shap_336 <- read_rds(here::here(path_models, 
                              "outer_shaps_1week_336_v1_nested_main.rds")) |> 
  group_by(variable) |> 
  # Z score variables by individual feature items
  mutate(feature_score_z = (rfvalue - mean(rfvalue))/sd(rfvalue)) |> 
  # Put future efficacy in correct direction
  mutate(feature_score_z = if_else(str_detect(variable, "ema_10"),
                                        feature_score_z * (-1),
                                        feature_score_z)) |> 
  # normalize feature score to 0-1 scale
  mutate(feature_score_z_scaled = (feature_score_z - min(feature_score_z))/(max(feature_score_z)-min(feature_score_z))) |> 
  glimpse()
```



## Group Shapleys

```{r}
shap_0 <- shap_0 |>
  ungroup() |> 
  mutate(variable_grp = if_else(str_detect(variable, "lapse."), 
                           "past use (EMA item)", 
                           variable),
           variable_grp = if_else(str_detect(variable_grp, "ema_2"), 
                           "craving (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_3"), 
                           "past risky situation (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_4"), 
                           "past stressful event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_5"), 
                           "past pleasant event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_6"), 
                           "valence (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_7"), 
                           "arousal (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_8"), 
                           "future risky situation (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_9"), 
                           "future stressful event (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_10"), 
                           "future efficacy (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "missing."), 
                           "missing surveys (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "day"), 
                           "day of week (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "hour"), 
                           "time of day (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "age"), 
                           "age (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "sex"), 
                           "sex (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "marital"), 
                           "marital (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "race"), 
                           "race (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "educ"), 
                           "education (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "income"), 
                           "income (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "employ"), 
                           "employment (demographic)", 
                           variable_grp)) |>
  mutate(variable_grp = factor(variable_grp)) |> 
  group_by(id_obs, variable_grp) |> # values are already averaged across repeats
  summarize(shapley_value = sum(value),
            feature_value = mean(feature_score_z_scaled)) |> 
  mutate(model = "0 lag") |>
  ungroup()

shap_0 |> 
  write_rds(here::here(path_models, "outer_shapsgrp_1week_0_v1_nested_main.rds"))
```


```{r}
shap_24 <- shap_24 |>
  ungroup() |> 
  mutate(variable_grp = if_else(str_detect(variable, ".lapse"), 
                           "past use (EMA item)", 
                           variable),
           variable_grp = if_else(str_detect(variable_grp, "ema_2"), 
                           "craving (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_3"), 
                           "past risky situation (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_4"), 
                           "past stressful event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_5"), 
                           "past pleasant event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_6"), 
                           "valence (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_7"), 
                           "arousal (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_8"), 
                           "future risky situation (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_9"), 
                           "future stressful event (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_10"), 
                           "future efficacy (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "count.ema"), 
                           "missing surveys (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "day"), 
                           "day of week (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "hour"), 
                           "time of day (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "age"), 
                           "age (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "sex"), 
                           "sex (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "marital"), 
                           "marital (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "race"), 
                           "race (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "educ"), 
                           "education (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "income"), 
                           "income (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "employ"), 
                           "employment (demographic)", 
                           variable_grp)) |>
  mutate(variable_grp = factor(variable_grp)) |> 
  group_by(id_obs, variable_grp) |> # values are already averaged across repeats
  summarize(shapley_value = sum(value),
            feature_value = mean(feature_score_z_scaled)) |> 
  mutate(model = "24 lag") |>
  ungroup()

shap_24 |> 
  write_rds(here::here(path_models, "outer_shapsgrp_1week_24_v1_nested_main.rds"))
```


```{r}
shap_72 <- shap_72 |>
  ungroup() |> 
  mutate(variable_grp = if_else(str_detect(variable, ".lapse"), 
                           "past use (EMA item)", 
                           variable),
           variable_grp = if_else(str_detect(variable_grp, "ema_2"), 
                           "craving (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_3"), 
                           "past risky situation (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_4"), 
                           "past stressful event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_5"), 
                           "past pleasant event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_6"), 
                           "valence (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_7"), 
                           "arousal (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_8"), 
                           "future risky situation (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_9"), 
                           "future stressful event (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_10"), 
                           "future efficacy (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "count.ema"), 
                           "missing surveys (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "day"), 
                           "day of week (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "hour"), 
                           "time of day (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "age"), 
                           "age (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "sex"), 
                           "sex (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "marital"), 
                           "marital (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "race"), 
                           "race (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "educ"), 
                           "education (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "income"), 
                           "income (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "employ"), 
                           "employment (demographic)", 
                           variable_grp)) |>
  mutate(variable_grp = factor(variable_grp)) |> 
  group_by(id_obs, variable_grp) |> # values are already averaged across repeats
  summarize(shapley_value = sum(value),
            feature_value = mean(feature_score_z_scaled)) |> 
  mutate(model = "72 lag") |>
  ungroup()

shap_72 |> 
  write_rds(here::here(path_models, "outer_shapsgrp_1week_72_v1_nested_main.rds"))
```

```{r}
shap_168 <- shap_168 |>
  ungroup() |> 
  mutate(variable_grp = if_else(str_detect(variable, ".lapse"), 
                           "past use (EMA item)", 
                           variable),
           variable_grp = if_else(str_detect(variable_grp, "ema_2"), 
                           "craving (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_3"), 
                           "past risky situation (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_4"), 
                           "past stressful event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_5"), 
                           "past pleasant event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_6"), 
                           "valence (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_7"), 
                           "arousal (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_8"), 
                           "future risky situation (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_9"), 
                           "future stressful event (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_10"), 
                           "future efficacy (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "count.ema"), 
                           "missing surveys (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "day"), 
                           "day of week (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "hour"), 
                           "time of day (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "age"), 
                           "age (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "sex"), 
                           "sex (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "marital"), 
                           "marital (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "race"), 
                           "race (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "educ"), 
                           "education (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "income"), 
                           "income (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "employ"), 
                           "employment (demographic)", 
                           variable_grp)) |>
  mutate(variable_grp = factor(variable_grp)) |> 
  group_by(id_obs, variable_grp) |> # values are already averaged across repeats
  summarize(shapley_value = sum(value),
            feature_value = mean(feature_score_z_scaled)) |> 
  mutate(model = "168 lag") |>
  ungroup()

shap_168 |> 
  write_rds(here::here(path_models, "outer_shapsgrp_1week_168_v1_nested_main.rds"))
```


```{r}
shap_336 <- shap_336 |>
  ungroup() |> 
  mutate(variable_grp = if_else(str_detect(variable, ".lapse"), 
                           "past use (EMA item)", 
                           variable),
           variable_grp = if_else(str_detect(variable_grp, "ema_2"), 
                           "craving (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_3"), 
                           "past risky situation (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_4"), 
                           "past stressful event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_5"), 
                           "past pleasant event (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_6"), 
                           "valence (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_7"), 
                           "arousal (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_8"), 
                           "future risky situation (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_9"), 
                           "future stressful event (EMA item)",
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "ema_10"), 
                           "future efficacy (EMA item)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "count.ema"), 
                           "missing surveys (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "day"), 
                           "day of week (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "hour"), 
                           "time of day (other)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "age"), 
                           "age (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "sex"), 
                           "sex (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "marital"), 
                           "marital (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "race"), 
                           "race (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "educ"), 
                           "education (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "income"), 
                           "income (demographic)", 
                           variable_grp),
           variable_grp = if_else(str_detect(variable_grp, "employ"), 
                           "employment (demographic)", 
                           variable_grp)) |>
  mutate(variable_grp = factor(variable_grp)) |> 
  group_by(id_obs, variable_grp) |> # values are already averaged across repeats
  summarize(shapley_value = sum(value),
            feature_value = mean(feature_score_z_scaled)) |> 
  mutate(model = "336 lag") |>
  ungroup()

shap_336 |> 
  write_rds(here::here(path_models, "outer_shapsgrp_1week_336_v1_nested_main.rds"))
```

Downsize to 10% of obs

```{r}
downsample_ratio <- .10
ids_0 <- shap_0 |>
  pull(id_obs) |>
  unique()
ids_0 <- ids_0 |> sample(size = round(length(ids_0)/(1/downsample_ratio)))
ids_24 <- shap_24 |>
  pull(id_obs) |>
  unique()
ids_24 <- ids_24 |> sample(size = round(length(ids_24)/(1/downsample_ratio)))
ids_72<- shap_72 |>
  pull(id_obs) |>
  unique()
ids_72 <- ids_72 |> sample(size = round(length(ids_72)/(1/downsample_ratio)))
ids_168<- shap_168 |>
  pull(id_obs) |>
  unique()
ids_168 <- ids_168 |> sample(size = round(length(ids_168)/(1/downsample_ratio)))
ids_336<- shap_336|>
  pull(id_obs) |>
  unique()
ids_336 <- ids_336 |> sample(size = round(length(ids_336)/(1/downsample_ratio)))

shap_down_0 <- shap_0 |> 
  filter(id_obs %in% ids_0)

shap_down_24 <- shap_24 |> 
 filter(id_obs %in% ids_24)

shap_down_72 <- shap_72 |> 
  filter(id_obs %in% ids_72)

shap_down_168 <- shap_168 |> 
  filter(id_obs %in% ids_168)

shap_down_336 <- shap_336 |> 
  filter(id_obs %in% ids_336)
```

Save out local tibbles
```{r}
shap_down_0 |> 
  write_rds(here::here(path_models,
                       "outer_shapsgrp_1week_0_v1_nested_main_downsized.rds"))
shap_down_24 |> 
  write_rds(here::here(path_models,
                       "outer_shapsgrp_1week_24_v1_nested_main_downsized.rds"))
shap_down_72 |> 
  write_rds(here::here(path_models,
                       "outer_shapsgrp_1week_72_v1_nested_main_downsized.rds"))
shap_down_168 |> 
  write_rds(here::here(path_models,
                       "outer_shapsgrp_1week_168_v1_nested_main_downsized.rds"))
shap_down_336 |> 
  write_rds(here::here(path_models,
                       "outer_shapsgrp_1week_336_v1_nested_main_downsized.rds"))
```

## Global Shapley

```{r}
shap_global_0 <- shap_0 |>
  group_by(model, variable_grp) |>
  summarize(mean_value = mean(abs(shapley_value)), .groups = "drop") |>
  arrange(mean_value) 

shap_global_24 <- shap_24 |>
  group_by(model, variable_grp) |>
  summarize(mean_value = mean(abs(shapley_value)), .groups = "drop") |>
  arrange(mean_value) 

shap_global_72 <- shap_72 |>
  group_by(model, variable_grp) |>
  summarize(mean_value = mean(abs(shapley_value)), .groups = "drop") |>
  arrange(mean_value) 

shap_global_168 <- shap_168 |>
  group_by(model, variable_grp) |>
  summarize(mean_value = mean(abs(shapley_value)), .groups = "drop") |>
  arrange(mean_value) 

shap_global_336 <- shap_336 |>
  group_by(model, variable_grp) |>
  summarize(mean_value = mean(abs(shapley_value)), .groups = "drop") |>
  arrange(mean_value) 


shap_global_all <- shap_global_0 |>
  bind_rows(shap_global_24) |>
  bind_rows(shap_global_72) |>
  bind_rows(shap_global_168) |>
  bind_rows(shap_global_336) 
```

Save out global tibble
```{r}
shap_global_all |> 
  write_rds(here::here(path_models, "shap_global_all.rds"))
```





