---
title: Lagged Predictions of Next Week Alcohol Use for Precision Mental Health Support 
author:
  - name: Kendra Wyant 
    corresponding: false
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
  - name: Jiachen (Coco) Yu 
    corresponding: false
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
  - name: Gaylen E. Fronk 
    corresponding: false
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
  - name: John J. Curtin 
    corresponding: true
    email: jjcurtin@wisc.edu
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison 
keywords:
  - Substance use disorders
  - Precision mental health 
abstract: |
  This study found some pretty cool results that have both high impact and important clinical implications.  For example ...
date: last-modified
bibliography: paper_lag.bib
citation:
  container-title: Journal of Important Findings 
number-sections: false 
---


<!--Notes:
Target journal: Clinical Psychological Science 
Format: Brief empirical report (5,000 words)

Brief Empirical Reports. Brief empirical reports will have a 5,000-word limit, inclusive of front (title page) and back matter (references, footnotes). Articles are limited to a total combination of 4 tables and figures (e.g., 2 tables and 2 figures) that are not part of the word limit. Each table or figure should occupy no more than one printed page. An abstract (maximum of 150 words) is included in the word limit.

Empirical Articles. Empirical Articles should aim for a 12,000-word maximum, inclusive of front (title page) and back matter (references, footnotes, appendices). Articles are limited to a total combination of 6 tables and figures (e.g., 4 tables and 2 figures) that are not part of the word limit. Each table or figure should occupy no more than one printed page. Reporting of multiple investigations within a single manuscript is encouraged, and length adjustments can be discussed if and as needed. An abstract (maximum of 150 words) is included in the word limit. -->



<!-- Results figs/tables (4 total):

1. Demographics table
2. figure with auroc and confidence interval by lag 
3. figure with auroc and confidence interval by protected group and lag 
4. figure for Shapley values

Distributions of posterior probabilities in supplemental 
Histograms of predicted probabilities in supplemental-->


## Introduction

### Precision Medicine

Precision medicine has been a goal in healthcare for over half a century [@derubeisHistoryCurrentStatus2019]. Today, this approach is also applied to chronic mental health conditions, like substance use disorders (SUDs), under the term *precision mental health*. Precision mental health uses individual characteristics to guide initial treatment matching and adaptive continuing care over time. It requires dense, long-term monitoring of symptoms and related states, for interventions to be tailored to an individual's needs and preferences at any given moment [@bickmanAchievingPrecisionMental2016]. Essentially, it aims to identify both *when* and *how* to intervene.

### Personal Sensing and Machine Learning

Using algorithms to time (*when*) and select personalized interventions (*how*) for substance use may now be possible, thanks to personal sensing and high-dimensional machine learning algorithms. Personal sensing allows for frequent, longitudinal monitoring of individuals' affect, behavior, and cognitions in their day-to-day lives [@mohrPersonalSensingUnderstanding2017]. These data can then be used as inputs for machine learning algorithms to predict the probability of specific outcomes (e.g., lapse risk) and identify the top features contributing to those predictions.

### EMA

Ecological momentary assessment (EMA) may be particularly well-suited for these algorithms. It offers momentary subjective insight into constructs that can be easily mapped onto modular forms of treatment, such as the relapse prevention model [@marlattRelapsePreventionMaintenance1985; @witkiewitzRelapsePreventionAlcohol2004]. EMA also appears to be well tolerated by individuals with substance use disorders [@wyantAcceptabilityPersonalSensing2023]. Thus, it can serve as an important signal for predicting substance use outcomes and interpreting clinically relevant features over a sustained period.

### Preliminary Promising Work

Preliminary promising work suggests it is possible to build EMA models that predict immediate lapses back to substance use [@waltersUsingMachineLearning2021; @baeMobilePhoneSensors2018; @soysterPooledPersonspecificMachine2022; @chihPredictiveModelingAddiction2014]. In a previous study from our group, we demonstrated that we can do this very well. Model features were engineered from raw scores and longitudinal change in responses to 4X daily EMAs. EMA questions were designed to measure theoretically-implicated risk factors including past use, craving, past pleasant events, past and future risky situations, past and future stressful events, emotional valence and arousal, and self-efficacy [for reviews, see @marlattRelapsePreventionMaintenance1985; @fronkStressAllostasisSubstance2020; @witkiewitzModelingComplexityPosttreatment2007]. We showed that it was possible to predict immediate alcohol lapses within the next week, day, and hour with clinically meaningful accuracy, area under the receiver operating curves (auROCs) of 0.89, 0.90, and 0.93, respectively [@wyantMachineLearningModels2023]. We also characterized the relative importance of features contributing to these risk probabilities for specific individuals at specific moments in time. These models are well-suited for just-in-time adaptive interventions (JITAIs) integrated within an app to address these immediate risks.

### Many Interventions Happen Outside of an App

However, some interventions take time to set up. For example, someone who has reported recent past alcohol use and low abstinence self-efficacy might be encouraged to attend a self-help meeting, plan an outing with important people in their life, or schedule an appointment with a therapist. These multimodal interventions (i.e., combined human and digital interventions) are not available 24/7. A "time-lagged" model with predictions shifted further into the future  could provide patients with increased lead time to implement supports that might not be immediately available to them.

### Current Study

In this study, we compare the performance of one of our models from a previous study with models featuring increased lag time between predictions and outcomes. Specifically, we use the same EMA features as our immediate model and train new models to predict the probability of a lapse beginning one day (24 hours), three days (72 hours), one week (168 hours), or two weeks (336 hours) into the future. Our primary objective is to assess how model performance degrades with increasing lag time.





## Methods

<!--info moved from preregistration-->

### Participants

We recruited participants in early recovery (1-8 weeks of abstinence) from moderate to severe alcohol use disorder in Madison, Wisconsin, US for a three month longitudinal study. We used data from all participants included in our previous study (N = 151; see [@wyantMachineLearningModels2023] for enrollment, disposition, and demographic information).

### Lapse Labels

We predicted lapses occurring in one week windows. Predictions were updated hourly. Therefore our models provided hour-by-hour predictions of future probability of an alcohol lapse within a one week window shifted at various time points (i.e., lags) into the future (no lag and one day, three day, one week, or two week lagged predictions). The first prediction for each participant occurs 24 hours + lag time (in hours) after their study start date. For example, the first prediction for the one day lagged prediction model would be 48 hours after participants' start date.

A prediction window was labeled *lapse* if the start date/hour of any drinking episode fell within that window. A window was labeled *no lapse* if no alcohol use occurred within that window +/- 6 hours. If no alcohol use occurred within the window but did occur within 6 hours of the start or end of the window, the window was excluded. We had previously used a more conservative fence around lapse exclusions (24 hours vs. 6 hours), however, after re-evaluation we deemed this to be too conservative.

### Feature Engineering

Features were calculated using only data collected before the start of each prediction window. For our no lag models this included all data prior to the hour of the start of the prediction window. For our lagged models, the last EMA data used for feature engineering were collected up to one day, three days, one week, or two weeks prior to the start of the prediction window.

Following our previous work, features were derived from three data sources:

-   *Demographics*: We created quantitative features for age and personal income, and dummy-coded features for sex, race/ethnicity, marital status, education, and employment.

-   *Day and time of prediction window onset*: We created dummy-coded features to indicate time of day and day of week that the prediction window began.

-   *Previous EMA responses*: We created raw EMA and change features for varying scoring epochs before the start of the prediction window for all EMA items (i.e., 12, 24, 48, 72, and 168 hours). Raw features included min, max, and median scores for each EMA question across all EMAs in each epoch for that participant. We calculated change features by subtracting the participant's mean score for each EMA question (using all EMAs collected before the start of the prediction window) from the associated raw feature. We also created raw and change features based on the most recent response for each EMA question and raw and change rate features from previously reported lapses.

### Modeling Decisions

Our primary performance metric for model selection and evaluation will be auROC.

We will consider four candidate statistical algorithms including elastic net, XGBoost, regularized discriminant analysis (rda), and single layer neural networks. This will ensure we are considering algorithms that differ in terms of bias-variance tradeoff (e.g., parametric vs non-parametric) to select the model configuration that most closely represents the true data generating process.

We will use participant-grouped, nested cross-validation for model training, selection, and evaluation with auROC. We will use 1 repeat of 10-fold cross-validation for the inner loops (i.e., *validation* sets) and 3 repeats of 10-fold cross-validation for the outer loop (i.e., *test* sets).

Best model configurations will be selected using median auROC across the 10 validation sets. Final performance evaluation of those best model configurations used median auROC across the 30 test sets.

## Results



## Discussion

## References
