---
title: "Supplemental Figures and Tables" 
author: "Kendra Wyant"
date: "`r May 20, 2024"
number-sections: true
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true"))
suppressPackageStartupMessages(library(tidyposterior))


theme_set(theme_classic())

path_models_lag <- format_path(str_c("studydata/risk/models/lag"))
```


```{r}
pp_tidy <- read_csv(here::here(path_models_lag, "pp_tidy.csv"), 
                                 show_col_types = FALSE) 

ci <- read_csv(here::here(path_models_lag, "test_metrics_all_pp_perf.csv"), 
                                 show_col_types = FALSE) |> 
  mutate(model = factor(model, levels = c("0 lag", "24 lag", "72 lag", "168 lag", "336 lag"),
                        labels = c("0 hours", "24 hours", "72 hours", "168 hours", "336 hours")))

pp_dem <- read_csv(here::here(path_models_lag, "pp_dem_all.csv"), 
                                 show_col_types = FALSE)
```


## Supplemental Figures

### Figure S1: Full Posterior Distributions for auROC by Model

```{r}
#| echo: false
pp_tidy |> 
  mutate(model = factor(model, levels = c("lag0", "lag24", "lag72", "lag168", "lag336"),
                        labels = c("0 hours", "24 hours", "72 hours", "168 hours", "336 hours"))) |>
  ggplot() + 
  geom_histogram(aes(x = posterior), fill = "light grey", color = "black", alpha = .4, 
                 bins = 30) +
  geom_segment(mapping = aes(y = 1200, yend = 1600, x = pp_median, xend = pp_median),
               data = ci) +
  geom_segment(mapping = aes(y = 1400, yend = 1400, x = pp_lower, xend = pp_upper),
                data = ci) +
  facet_wrap(~model, ncol = 1) +
  scale_y_continuous("Posterior Probability", breaks = c(0, 500, 1000, 1500)) +
  xlab("Area Under ROC Curve") +
  theme_classic() +
  theme(legend.position = "none")
```

### Figure S2: Local Shapley Plots by Model

Read in data
```{r}
global_all <- read_rds(here::here(path_models_lag, "shap_global_all.rds")) |> 
   filter(!variable_grp %in% c("day of week (other)", "time of day (other)")) |> 
  mutate(variable_grp = str_remove(variable_grp, "(EMA item)"),
          variable_grp = str_remove(variable_grp, "(demographic)"),
          variable_grp = str_remove(variable_grp, "(other)"),
        variable_grp = str_remove(variable_grp, "[[:punct:]][[:punct:]]")) |> 
   mutate(variable_grp = reorder(variable_grp, mean_value, sum),
          model = factor(model, c("0 lag", "24 lag", "72 lag", "168 lag", "336 lag")))

shap_levels <- global_all |>
  mutate(variable_grp = reorder(variable_grp, mean_value, sum)) |>
  pull(variable_grp) |>
  levels()

shap_feat_0 <- read_rds(here::here(path_models_lag, "outer_shapsgrp_with_features_downsized_1week_0_v1_nested_main.rds")) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels))
  
shap_feat_24 <- read_rds(here::here(path_models_lag, "outer_shapsgrp_with_features_downsized_1week_24_v1_nested_main.rds")) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels))

shap_feat_72 <- read_rds(here::here(path_models_lag, "outer_shapsgrp_with_features_downsized_1week_72_v1_nested_main.rds")) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels))

shap_feat_168 <- read_rds(here::here(path_models_lag, "outer_shapsgrp_with_features_downsized_1week_168_v1_nested_main.rds")) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels))

shap_feat_336 <- read_rds(here::here(path_models_lag, "outer_shapsgrp_with_features_downsized_1week_336_v1_nested_main.rds")) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels))
```


```{r}
panel_shap_local_0 <- shap_feat_0 |>
  filter(!is.na(variable_grp)) |> 
  # scale feat score to 0-1
  mutate(feature_score = (feature_score_z_mean - min(feature_score_z_mean))/(max(feature_score_z_mean)-min(feature_score_z_mean))) |> 
  ggplot(mapping = aes(x = variable_grp, y = value, color = feature_score)) +
  ggforce::geom_sina(method = "counts", maxwidth = .7, alpha = .4) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-2, 5), breaks = seq(-2, 5)) +
  ylab("Shapley Value (0 Hour Lag)") +
  xlab(NULL) +
  scale_color_gradientn(colors = c("#240e31", "#f9e79f"),
                        breaks = c(.1, .9),
                        labels = c("low", "high")) +
  labs(color = NULL) +
  theme(legend.position = "right",
        legend.key.size = unit(0.25, "cm"),
        axis.text=element_text(size=9.5),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))+
  coord_flip()

panel_shap_local_24 <- shap_feat_24 |>
  filter(!is.na(variable_grp)) |> 
  # scale feat score to 0-1
  mutate(feature_score = (feature_score_z_mean - min(feature_score_z_mean))/(max(feature_score_z_mean)-min(feature_score_z_mean))) |> 
  ggplot(mapping = aes(x = variable_grp, y = value, color = feature_score)) +
  ggforce::geom_sina(method = "counts", maxwidth = .7, alpha = .4) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-2, 5), breaks = seq(-2, 5)) +
  ylab("Shapley Value (24 Hour Lag)") +
  xlab(NULL) +
  scale_color_gradientn(colors = c("#240e31", "#922488"),
                        breaks = c(.1, .9),
                        labels = c("low", "high")) +
  labs(color = NULL) +
  theme(legend.position = "right",
        legend.key.size = unit(0.25, "cm"),
        axis.text=element_text(size=9.5),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))+
  coord_flip()

panel_shap_local_72 <- shap_feat_72 |>
  filter(!is.na(variable_grp)) |> 
  # scale feat score to 0-1
  mutate(feature_score = (feature_score_z_mean - min(feature_score_z_mean))/(max(feature_score_z_mean)-min(feature_score_z_mean))) |> 
  ggplot(mapping = aes(x = variable_grp, y = value, color = feature_score)) +
  ggforce::geom_sina(method = "counts", maxwidth = .7, alpha = .4) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-2, 5), breaks = seq(-2, 5)) +
  ylab("Shapley Value (72 Hour Lag)") +
  xlab(NULL) +
  scale_color_gradientn(colors = c("#240e31", "#458892"),
                        breaks = c(.1, .9),
                        labels = c("low", "high")) +
  labs(color = NULL) +
  theme(legend.position = "right",
        legend.key.size = unit(0.25, "cm"),
        axis.text=element_text(size=9.5),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))+
  coord_flip()

panel_shap_local_168 <- shap_feat_168 |>
  filter(!is.na(variable_grp)) |> 
  # scale feat score to 0-1
  mutate(feature_score = (feature_score_z_mean - min(feature_score_z_mean))/(max(feature_score_z_mean)-min(feature_score_z_mean))) |> 
  ggplot(mapping = aes(x = variable_grp, y = value, color = feature_score)) +
  ggforce::geom_sina(method = "counts", maxwidth = .7, alpha = .4) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-2, 5), breaks = seq(-2, 5)) +
  ylab("Shapley Value (168 Hour Lag)") +
  xlab(NULL) +
  scale_color_gradientn(colors = c("#240e31", "#75f3d3"),
                        breaks = c(.1, .9),
                        labels = c("low", "high")) +
  labs(color = NULL) +
  theme(legend.position = "right",
        legend.key.size = unit(0.25, "cm"),
        axis.text=element_text(size=9.5),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))+
  coord_flip()
```



```{r}
#| label: fig-shap-local
#| fig-cap: "Local feature importance plots by model."
#| fig-height: 7
#| fig-width: 7

cowplot::plot_grid(panel_shap_local_0, panel_shap_local_24,
                   panel_shap_local_72, panel_shap_local_168,
                   ncol = 2, labels = c("A", "B", "C", "D"), 
                   align = "hv")

```


### Figure S3: Individual Shapley Plots for Top Features

Past use
```{r}
shap_feat_336 |> 
  filter(variable_grp == "past use ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Past Use", y = "Shapley (336 Hour Lag)", x = "Feature value")

shap_feat_0 |> 
  filter(variable_grp == "past use ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Past Use", y = "Shapley (0 Hour Lag)", x = "Feature value")

shap_feat_24 |> 
  filter(variable_grp == "past use ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Past Use", y = "Shapley (24 Hour Lag)", x = "Feature value")

shap_feat_72 |> 
  filter(variable_grp == "past use ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Past Use", y = "Shapley (72 Hour Lag)", x = "Feature value")

shap_feat_168 |> 
  filter(variable_grp == "past use ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Past Use", y = "Shapley (168 Hour Lag)", x = "Feature value")
```

future efficacy
```{r}
shap_feat_336 |> 
  filter(variable_grp == "future efficacy ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Efficacy", y = "Shapley (336 Hour Lag)", x = "Feature value")

shap_feat_0 |> 
  filter(variable_grp == "future efficacy ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Efficacy", y = "Shapley (0 Hour Lag)", x = "Feature value")

shap_feat_24 |> 
  filter(variable_grp == "future efficacy ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Efficacy", y = "Shapley (24 Hour Lag)", x = "Feature value")

shap_feat_72 |> 
  filter(variable_grp == "future efficacy ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Efficacy", y = "Shapley (72 Hour Lag)", x = "Feature value")

shap_feat_168 |> 
  filter(variable_grp == "future efficacy ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Efficacy", y = "Shapley (168 Hour Lag)", x = "Feature value")
```

Income
```{r}
shap_feat_336 |> 
  filter(variable_grp == "income ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Income", y = "Shapley (336 Hour Lag)", x = "Feature value")

shap_feat_0 |> 
  filter(variable_grp == "income ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Income", y = "Shapley (0 Hour Lag)", x = "Feature value")

shap_feat_24 |> 
  filter(variable_grp == "income ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Income", y = "Shapley (24 Hour Lag)", x = "Feature value")

shap_feat_72 |> 
  filter(variable_grp == "income ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Income", y = "Shapley (72 Hour Lag)", x = "Feature value")

shap_feat_168 |> 
  filter(variable_grp == "income ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Income", y = "Shapley (168 Hour Lag)", x = "Feature value")
```

Craving
```{r}
shap_feat_336 |> 
  filter(variable_grp == "craving ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Craving", y = "Shapley (336 Hour Lag)", x = "Feature value")

shap_feat_0 |> 
  filter(variable_grp == "craving ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Craving", y = "Shapley (0 Hour Lag)", x = "Feature value")

shap_feat_24 |> 
  filter(variable_grp == "craving ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Craving", y = "Shapley (24 Hour Lag)", x = "Feature value")

shap_feat_72 |> 
  filter(variable_grp == "craving ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Craving", y = "Shapley (72 Hour Lag)", x = "Feature value")

shap_feat_168 |> 
  filter(variable_grp == "craving ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Craving", y = "Shapley (168 Hour Lag)", x = "Feature value")
```

Future Risky Situation
```{r}
shap_feat_336 |> 
  filter(variable_grp == "future risky situation ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Risky Situation", y = "Shapley (336 Hour Lag)", x = "Feature value")

shap_feat_0 |> 
  filter(variable_grp == "future risky situation ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Risky Situation", y = "Shapley (0 Hour Lag)", x = "Feature value")

shap_feat_24 |> 
  filter(variable_grp == "future risky situation ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Risky Situation", y = "Shapley (24 Hour Lag)", x = "Feature value")

shap_feat_72 |> 
  filter(variable_grp == "future risky situation ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Risky Situation", y = "Shapley (72 Hour Lag)", x = "Feature value")

shap_feat_168 |> 
  filter(variable_grp == "future risky situation ") |> 
  ggplot(aes(x = feature_score_z_mean, y = value)) +
  geom_point(alpha = .4) +
  labs(title = "Future Risky Situation", y = "Shapley (168 Hour Lag)", x = "Feature value")
```

## Supplemental Tables

### Table S1: Model performance by Demographic Group

```{r}
pp_dem <- pp_dem |> 
  mutate(lag = factor(lag, levels = c(0, 24, 72, 168, 336), 
                        labels = c("0 hours", "24 hours", "72 hours", "168 hours", "336 hours" )),
         model = factor(model, levels = c("not white", "non-hispanic white",
                                        "female", "male",
                                        "below poverty", "above poverty"))) |> 
  arrange(model, lag)

pp_dem_all <- pp_dem |> 
  filter(lag == "0 hours") |> 
  mutate(pp_lower = round(pp_lower, 3),
         pp_upper = round(pp_upper, 3),
         ci = str_c(pp_lower,"-",pp_upper)) |>
  select(-c(lag, pp_lower, pp_upper)) |> 
  bind_cols(pp_dem |> 
  filter(lag == "24 hours") |> 
  mutate(pp_lower = round(pp_lower, 3),
         pp_upper = round(pp_upper, 3),
         ci = str_c(pp_lower,"-",pp_upper)) |>
  select(-c(lag, pp_lower, pp_upper, model))) |> 
  bind_cols(pp_dem |> 
  filter(lag == "72 hours") |> 
  mutate(pp_lower = round(pp_lower, 3),
         pp_upper = round(pp_upper, 3),
         ci = str_c(pp_lower,"-",pp_upper)) |>
  select(-c(lag, pp_lower, pp_upper, model))) |> 
  bind_cols(pp_dem |> 
  filter(lag == "168 hours") |> 
  mutate(pp_lower = round(pp_lower, 3),
         pp_upper = round(pp_upper, 3),
         ci = str_c(pp_lower,"-",pp_upper)) |>
  select(-c(lag, pp_lower, pp_upper, model))) |> 
  bind_cols(pp_dem |> 
  filter(lag == "336 hours") |> 
  mutate(pp_lower = round(pp_lower, 3),
         pp_upper = round(pp_upper, 3),
         ci = str_c(pp_lower,"-",pp_upper)) |>
  select(-c(lag, pp_lower, pp_upper, model))) |> 
  add_row(model = "Race/Ethnicity", .before = 1) |> 
  add_row(model = "Sex at Birth", .before = 4) |> 
  add_row(model = "Income", .before = 7) |> 
  suppressMessages()
```

```{r}
#| label: tbl-fairness
#| tbl-cap: "Model Performance by Demographic Group"

pp_dem_all |> 
  mutate(across(c(pp_median...2, pp_median...4, pp_median...6, pp_median...8, pp_median...10), 
                ~round(., 3)),
         across(where(is.numeric), as.character)) |> 
  add_row(model = "Group",
          pp_median...2 = "Median auROC",
          ci...3 = "Bayesian CI",
          pp_median...4 = "Median auROC",
          ci...5 = "Bayesian CI",
          pp_median...6 = "Median auROC",
          ci...7 = "Bayesian CI",
          pp_median...8 = "Median auROC",
          ci...9 = "Bayesian CI",
          pp_median...10 = "Median auROC",
          ci...11 = "Bayesian CI",
          .before = 1) |> 
  knitr::kable(col.names = c("", "0 Lag", "",
                    "24 Lag", "", 
                   "72 Lag", "",
                    "168 Lag", "",
                   "336 Lag", "")) 
```

