# Apptainer build file

universe = vanilla
log = interactive.log

# If your build job needs access to any files in your /home directory, transfer them to your job using transfer_input_files
transfer_input_files = train.def,  outer_shaps_1week_72_v1_nested_main_batch1.rds, outer_shaps_1week_72_v1_nested_main_batch2.rds, outer_shaps_1week_72_v1_nested_main_batch3.rds, outer_shaps_1week_72_v1_nested_main_batch4.rds, outer_shaps_1week_72_v1_nested_main_batch5.rds

+IsBuildJob = true
request_cpus = 1
request_memory = 400GB
request_disk = 20GB

queue
